### ISSUE TITLE
Minification of Html Fails one some embedded Styles

### ISSUE THREAD

**Issue by JohnBergman** [Taritsyn/WebMarkupMin#60]
<style>
    .bgImageProfileCard_24897 {
      background: linear-gradient(to bottom, linear-gradient(to bottom, rgba(252, 204, 80, 0.80), rgba(249, 191, 42, 0.80)), url('/media/14886/25a2f705b44f45aa8ba1d56f0eb03644.png?anchor=center&mode=crop&width=400&height=300&rnd=131583440970000000') no-repeat;
    }
</style>

An error occurred while Minifying Html: 

Category: : CSS_MINIFICATION_ERROR
Message: : Expected function, found ';'
File: : /....[snipped].../6hourcharter
Line Number: : 1807
Column Number: : 260
Source Fragment::

Line 1806: 
Line 1807: …0&height=300&rnd=131583440970000000') no-repeat;
------------------------------------------------------------^
Line 1808:

**Comment by JohnBergman** [comment]
Further testing without the no-repeat yielded the same results, removing the semi-colon, and the error moves to the closing brace.  The inline style works as expected on the web page.

**Comment by Taritsyn** [comment]
Hello, John!

It looks like you forgot to close parenthesis:

```css
<style>
.bgImageProfileCard_24897
{
	background: linear-gradient(to bottom, linear-gradient(to bottom, rgba(252, 204, 80, 0.80), rgba(249, 191, 42, 0.80))), url('/media/14886/25a2f705b44f45aa8ba1d56f0eb03644.png?anchor=center&mode=crop&width=400&height=300&rnd=131583440970000000') no-repeat;
}
</style>
```

**Comment by Taritsyn** [comment]
There is also another variant:

```css
<style>
.bgImageProfileCard_24897
{
	background: linear-gradient(to bottom, rgba(252, 204, 80, 0.80), rgba(249, 191, 42, 0.80)), url('/media/14886/25a2f705b44f45aa8ba1d56f0eb03644.png?anchor=center&mode=crop&width=400&height=300&rnd=131583440970000000') no-repeat;
}
</style>
```
